### ISSUE TITLE
github api requires TLS 1.2

### ISSUE THREAD

**Issue by petersendev** [giuliov/hugo-vsts-extension#2]
Currently the task fails with the error
> The request was aborted: Could not create SSL/TLS secure channel.

GitHub requires TLS 1.2 since Feb 22 2018, see https://githubengineering.com/crypto-removal-notice/

PR incoming.

**Comment by giuliov** [comment]
I saw the news but didn't realize it might impact me 😳

**Comment by KodeAndGame** [comment]
Has this been released? I'm still seeing the below error in my logs and wondering if I missed something:

`2018-03-04T10:16:28.5999095Z ##[error]The request was aborted: Could not create SSL/TLS secure channel.
2018-03-04T10:16:28.6383937Z ##[section]Finishing: Hugo generate 
`

**Comment by KodeAndGame** [comment]
Sorry - I can see now that it has not been [released](https://marketplace.visualstudio.com/items?itemName=giuliovdev.hugo-extension). Can you please update with a comment when released?
