### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by tigrannajaryan** [giuliov/hugo-vsts-extension#4]
I am trying to build by Hugo static web using this extension and the following error. My best guess is it fails when it attempts to download Hugo executable. 

```
******************************************************************************
Starting: Hugo generate
******************************************************************************
==============================================================================
Task         : Hugo
Description  : Generate a static web site using Hugo, a Fast and Flexible Website Generator
Version      : 1.0.0
Author       : Giulio Vian
Help         : [More Information on Task](https://github.com/giuliov/hugo-vsts-extension/README.md), for [Information on Hugo](https://gohugo.io/).
==============================================================================
The request was aborted: Could not create SSL/TLS secure channel.
******************************************************************************
Finishing: Hugo generate
******************************************************************************
```

Here are my settings:

![screenshot_1](https://user-images.githubusercontent.com/4194920/37247165-20b1b2c4-2485-11e8-92b4-d6aaaf1263a6.png)

Is there any other information I can supply to help diagnose? Thank you.

**Comment by petersendev** [comment]
Hi, this is already fixed in code, but not deployed to the marketplace yet (waiting for the maintainer). See #2 (PR #3 )

As a workaround you can use this powershell script (just set BASEURL and HugoVersion variables):
https://gist.github.com/petersendev/ab08c5280d1a3705e43aa11d2148dca6
You can customize hugo parameters in the last line.

**Comment by tigrannajaryan** [comment]
Thanks, as a workaround I ended up committing hugo executable to my repo and calling it directly during the build.

**Comment by giuliov** [comment]
Sorry for the delay.
I updated the extension, let me know if you find any issue.
I close the ticket for now.

**Comment by jeromechrist** [comment]
@giuliov thx, builds are passing 👍
