### ISSUE TITLE
Build in VSTS is different from Local

### ISSUE THREAD

**Issue by MatthewMcD** [giuliov/hugo-vsts-extension#7]
Thanks for this extension!

I am trying to build a simple project as a test.
If I run `hugo --enableGitInfo --i18n-warnings --verbose --baseURL https://photos.foo.com`

On my local machine with hugo I get 50 pages and 33 static files. On the server I get 20 pages and 20 static files.

Any ideas why I would see different page counts?

**Comment by MatthewMcD** [comment]
Never mind. I wasn't choosing to "Checkout Submodules" on the get sources task. I forked the repo. I'd like to update your README file to include the settings and steps that made it work for me.

**Comment by giuliov** [comment]
Sure why not: PRs always welcome.

**Comment by MatthewMcD** [comment]
Thanks!
