### ISSUE TITLE
Possible issue with Extended Version support

### ISSUE THREAD

**Issue by nsio-admin** [giuliov/hugo-vsts-extension#9]
When running the Hugo generate task using the open source theme 'introduction', Azure Pipelines shows the following error:

> error:  failed to transform resource: POSTCSS: failed to transform "css/main.css" (text/css): PostCSS not found; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/

Hugo Version is set to latest and the Extended checkbox is checked.  When running Hugo manually, the above error is typically generated when one forgets to download the extended version of Hugo, but perhaps there is something else I'm doing wrong here?

**Comment by nsio-admin** [comment]
It turns out that you have to "manually" install both postcss-cli and autoprefixer before running the Hugo task.  This is easily done by adding two npm tasks immediately prior to the Hugo task, with custom command lines:

install -g postcss-cli
install -g autoprefixer

This results in the Hugo task completing successfully (all other things being equal).

**Comment by giuliov** [comment]
Music to my hears, sorry for coming back so late but we were busy with "open-heart surgery" at work. Good work and thanks for appreciation.
